name: Build server
on:
  workflow_call:
jobs:
  build:
    name: Build server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove dev specific files
        run: rm -rfd node_modules .github .git .gitignore LICENSE README.md packages/client/*
        working-directory: .
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: .
