name: Build client
on:
  workflow_call:
jobs:
  build:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install Bun
        run: bun install
      - name: Run build
        run: bun run build
        working-directory: ./packages/client/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: |
            ./packages/client/dist/
            ./packages/client/packages.json
