name: Workflow - Build Server
on:
  workflow_call:
jobs:
  build:
    name: Job - Build Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step - Remove dev specific files
        run: rm -rfd node_modules .github .git .gitignore LICENSE README.md packages/client/* packages/client/.??*
        working-directory: .
      - name: Step - Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: .
