name: Deploy test
on: [push]
jobs: 
  call-build-client-workflow:
    uses: ./.github/workflows/build-client.yml
  call-build-server-workflow:
    uses: ./.github/workflows/build-server.yml    
  deploy:
    name: Job - Deploy test
    runs-on: ubuntu-latest
    needs: [call-build-client-workflow, call-build-server-workflow]
    environment: 
      name: ${{ github.event.inputs.env }}
    steps:
    - name: Step - Check environment variable
      run: |
        if [[ "${{ environment.name }}" == "Test" ]]; then
          echo "Deploying to test server..."
        elif [[ "${{ environment.name }}" == "Live" ]]; then
          echo "Deploying to live server..."
        else
          echo "Unknown environment - ${{ env.environment.name }}"
        exit 1
        fi
    - name: Step - Download server build artifacts
      uses: actions/download-artifact@v4
      with:
        name: server-build
        path: .
    - name: Step - Download client build artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-build
        path: ./packages/client/dist/
    - name: Step - Download client package.json artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-package-json
        path: ./packages/client/
    - name: Step - Deploy to test server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET_DIRECTORY }}
        EXCLUDE: "" 
        SCRIPT_BEFORE: |
          kill -15 bun
          rm -rf packages node_modules package.json bun.lockb
        SCRIPT_AFTER: |
          echo $RSYNC_STDOUT
          cd ${{ secrets.TARGET_DIRECTORY }}
          ~/.bun/bin/bun install
          bun packages/server/src/server.js
