name: Build Client and Deploy on Test
on: [push]
jobs:
  build:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install Bun
        run: bun install
      - name: Run build
        run: |
          ls
          bun run build
        working-directory: ./packages/client/
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: 
      name: Test
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: whoami
