name: Deploy Test
on: [push]
jobs: 
  deploy:
    name: Deploy Test
    runs-on: ubuntu-latest
    environment: 
      name: Test
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: ls
