name: Deploy Test
on: [push]
jobs: 
  call-build-client-workflow:
    uses: ./.github/workflows/build-client.yml
  deploy:
    name: Deploy Test
    runs-on: ubuntu-latest
    needs: call-build-client-workflow
    environment: 
      name: Test
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-build
        path: .
    - name: Deploy to Test server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET_DIRECTORY }}
        EXCLUDE: ""
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          mkdir testdir
          ls -al
          echo $RSYNC_STDOUT
