name: Workflow - Deploy

on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run tests against'
        type: environment
        required: true 

env:
  GH_TOKEN: ${{ github.token }}
  TARGET_ENV: ${{ github.event.inputs.env }}  

jobs: 
  check-env-var:
     if:  ${{ github.event.inputs.env != 'Test' && github.event.inputs.env != 'Live'}}
     name: Job - Check Environment Variable
     runs-on: ubuntu-latest
     steps:
       - name: INVALID ENVIRONMENT VARIABLE!
         run: exit 1

  call-build-client-workflow:
    name: Job - Call Build Client Workflow
    uses: ./.github/workflows/build-client.yml
    
  call-build-server-workflow:
    name: Job - Call Build Server Workflow
    uses: ./.github/workflows/build-server.yml    

  deploy-test:
    if:  ${{ github.event.inputs.env == 'Test' }}
    name: Job - Deploy to TEST server
    runs-on: ubuntu-latest
    needs: [call-build-client-workflow, call-build-server-workflow]
    environment: 
      name: Test
    
    steps:             
    - name: Step - Download server build artifacts
      uses: actions/download-artifact@v4
      with:
        name: server-build
        path: .
        
    - name: Step - Download client build artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-build
        path: ./packages/client/dist/
        
    - name: Step - Download client package.json artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-package-json
        path: ./packages/client/
        
    - name: Step - Deploy to server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET_DIRECTORY }}
        EXCLUDE: "" 
        SCRIPT_BEFORE: |
          killall -15 bun
          rm -rf packages node_modules package.json bun.lockb
        SCRIPT_AFTER: |
          echo $RSYNC_STDOUT
          cd ${{ secrets.TARGET_DIRECTORY }}
          ~/.bun/bin/bun install
          ~/.bun/bin/bun packages/server/src/server.js
          
  deploy-live:
    if:  ${{ github.event.inputs.env == 'Live' }}
    name: Job - Deploy to LIVE server
    runs-on: ubuntu-latest
    needs: [call-build-client-workflow, call-build-server-workflow]
    environment: 
      name: Live
    
    steps:             
    - name: Step - Download server build artifacts
      uses: actions/download-artifact@v4
      with:
        name: server-build
        path: .
        
    - name: Step - Download client build artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-build
        path: ./packages/client/dist/
        
    - name: Step - Download client package.json artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-package-json
        path: ./packages/client/
        
    - name: Step - Deploy to server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET_DIRECTORY }}
        EXCLUDE: "" 
        SCRIPT_BEFORE: |
          killall -15 bun
          rm -rf packages node_modules package.json bun.lockb
        SCRIPT_AFTER: |
          echo $RSYNC_STDOUT
          cd ${{ secrets.TARGET_DIRECTORY }}
          ~/.bun/bin/bun install
          ~/.bun/bin/bun packages/server/src/server.js
