name: Deploy Test
on: [push]
jobs: 
  call-build-client-workflow:
    uses: ./.github/workflows/build-client.yml
  call-build-server-workflow:
    uses: ./.github/workflows/build-server.yml    
  deploy:
    name: Deploy test
    runs-on: ubuntu-latest
    needs: [call-build-client-workflow, call-build-server-workflow]
    environment: 
      name: Test
    steps:
    - name: Download server build artifacts
      uses: actions/download-artifact@v4
      with:
        name: server-build
        path: .
    - name: Download client build artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-build
        path: ./packages/client/dist/
    - name: Download client packages.json artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-packages-json
        path: ./packages/client/
    - name: Deploy to test server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET_DIRECTORY }}
        EXCLUDE: "" 
        SCRIPT_BEFORE: ""
        SCRIPT_AFTER: |
          echo $RSYNC_STDOUT
          bun install
